#!/bin/bash
SNAP=20000
CLIENT=10000
FILE=cumul
GEN=cumulative
DATA=local
#DATA=ssh

mkargs(){
  ARGS="-g $GEN -t $DATA"
  ARGS="$ARGS -s $SNAP -c $CLIENT"
}

tufsim(){
  FNAME=$1.csv
  shift
  echo
  echo Creating $FNAME $ARGS
  time ./tufsim.rb $@ $ARGS -o $FNAME
}

sim_sc(){
  BASE=$1
  EXP=$2
  tufsim ${FILE}_sc skiplist -b $BASE -i $EXP
}

run_sim(){
  tufsim ${FILE}_diplomat diplomat
  tufsim ${FILE}_tuf tuf
  tufsim ${FILE}_sc height0 
  for base in 2 5 11 17; do
    sim_sc $base 5
  done
}

sim_cumul(){
  mkargs
  run_sim
}

sim_scatter(){
  GEN=scatter
  FILE=scatter
  mkargs
  run_sim
}

sim_random(){
  mkargs
  tufsim random_diplomat diplomat
  tufsim random_tuf tuf
  tufsim random_sc height0
  for base in 2 5 11 17; do
    tufsim random_sc skiplist -r $base -i 5
  done
}

sim_cumul
sim_scatter
sim_random
