#!/bin/bash
#SNAP=100000
CLIENT=100000
DATA=local
#DATA=ssh

mkargs(){
  ARGS="-g $1 -t $DATA"
  if [ "$SNAP" ]; then
    ARGS="$ARGS -s $SNAP -c $CLIENT"
  fi
}

tufsim(){
  FNAME=$1.csv
  shift
  echo
  echo Creating $FNAME $ARGS
  time ./tufsim.rb $@ $ARGS -o $FNAME
}

sim_sc(){
  BASE=$1
  EXP=$2
  tufsim ${FILE}_sc skiplist -b $BASE -i $EXP
}

run_sim(){
  FILE=$2
  mkargs $1
  tufsim $FILE diplomat
  tufsim $FILE tuf
  tufsim $FILE height0 
  sim_sc 2,5,11,17 5
}

sim_cumul(){
  run_sim cumulative cumul
}

sim_scatter(){
  run_sim scatter scatter
}

sim_random(){
  mkargs cumulative
  tufsim random diplomat
  tufsim random tuf
  tufsim random height0
  tufsim random_sc skiplist -r 1.0/2,1.0/5,1.0/11,1.0/17 -i 5
}

sim_cumul
sim_scatter
sim_random
